name: Docker Image Builder

on:
  pull_request:
    branches: master
  push:
    branches: master
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Invoke candidate repo entry script
      run: |
        wget https://github.com/arajkumar/f8a-server-backbone/archive/v2_changes.zip -O changes.zip
        unzip changes.zip -d changes
        mv changes/* .
 #   - name: Push to GitHub Packages
 #     uses: docker/build-push-action@v1
 #     with:
 #       username: ${{ github.actor }}
 #       password: ${{ secrets.GITHUB_TOKEN }}
 #       registry: docker.pkg.github.com
 #       repository: arajkumar/docker-builder/latest
 #       tag_with_ref: true
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ararunprasad/backbone_v2_gh
        tag_with_ref: true
