name: Docker Image Builder

on:
  pull_request:
    branches: master
  push:
    branches: master
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: fabric8-analytics/fabric8-analytics-server
        ref: master
    - run: ls -lh
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        repository: ararunprasad/backbone_v2_gh
        tags: test123
