name: Docker Image Builder

on:
  pull_request:
    branches: master
  push:
    branches: master
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Invoke candidate repo entry script
      run: |
        echo "FROM alpine:latest" > Dockerfile
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: arajkumar/my-repo/my-image
        tag_with_ref: true
